name: Unity Testing

on:
    pull_request: {}
    push: {}
    workflow_dispatch: {}

### Refer to https://game.ci/docs/github/getting-started
jobs:
    test:
        name: Run all tests ✨
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  lfs: true
            - uses: actions/cache@v3
              with:
                  path: Library
                  key: Library-test
            - uses: game-ci/unity-test-runner@v2
              id: testRunner
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
            #   with:
            #       githubToken: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/upload-artifact@v3
              with:
                  name: Test results (all modes)
                  path: ${{ steps.testRunner.outputs.artifactsPath }}
