name: Unity Build WebGL

on:
    workflow_dispatch: {}

### Refer to https://game.ci/docs/github/getting-started
jobs:
    build:
        name: Build for WebGL
        runs-on: ubuntu-latest
        steps:
            - name: Free Disk Space (Ubuntu)
              uses: jlumbroso/free-disk-space@main
              with:
                  dotnet: false
            - uses: actions/checkout@v3
              with:
                  lfs: true
            - uses: actions/cache@v3
              with:
                  path: Library
                  key: Library-WebGL
            - uses: game-ci/unity-builder@v2
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                  targetPlatform: WebGL
            - uses: actions/upload-artifact@v3
              with:
                  name: Build-WebGL
                  path: build
