name: Unity Build Addressable Windows

on:
    workflow_dispatch:
        inputs:
            customParameters:
                description: "build custom parameters"
                required: false
                default: ""
            build_type:
                description: "type of content build: update_build/complete_build"
                required: true
                default: "update_build"

### Refer to https://game.ci/docs/github/getting-started
jobs:
    buildForWindows:
        name: Build for StandaloneWindows
        runs-on: windows-2019
        steps:
            - uses: actions/checkout@v3
              with:
                  lfs: true
            - uses: actions/cache@v3
              with:
                  path: Library
                  key: Library-StandaloneWindows
            - uses: game-ci/unity-builder@v4
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                  buildMethod: UnityBuilderAction.BuildScript.${{ inputs.build_type }}
                  targetPlatform: StandaloneWindows
                  customParameters: "${{ inputs.customParameters }}"
            - uses: actions/upload-artifact@v3
              with:
                  name: ContentBuild-StandaloneWindows
                  path: Bundles
